// examples/react/src/todoItem.js
import React from 'react';
import classNames from 'classnames';
import {ESCAPE_KEY, ENTER_KEY} from './constants'

class TodoItem extends React.Component {
    constructor(props) {
        super(props);
        this.state = {editText: this.props.todo.title};
        this.textInput = null;
    }

    handleSubmit() {
        let val = !!this.state.editText ? this.state.editText.trim() : null;
        if (val) {
            this.props.onSave(val);
            this.setState({editText: val});
        } else {
            this.props.onDestroy();
        }
    }

    handleEdit() {
        this.props.onEdit();
        this.setState({editText: this.props.todo.title});
    }

    handleKeyDown(event) {
        if (event.which === ESCAPE_KEY) {
            this.setState({editText: this.props.todo.title});
            this.props.onCancel(event);
        } else if (event.which === ENTER_KEY) {
            this.handleSubmit(event);
        }
    }

    handleChange(event) {
        if (this.props.editing) {
            this.setState({editText: event.target.value});
        }
    }

    componentDidUpdate(prevProps) {
        if (!prevProps.editing && this.props.editing && this.textInput) {
            this.textInput.focus();
        }
    }

    render() {
        return (
            <li className={classNames({
                completed: this.props.todo.completed,
                editing: this.props.editing
            })}>
                <div className="view">
                    <input
                        className="toggle"
                        type="checkbox"
                        checked={this.props.todo.completed}
                        onChange={() => this.props.onToggle()}
                    />
                    <label onDoubleClick={() => this.handleEdit()}>
                        {this.props.todo.title}
                    </label>
                    <button className="destroy" onClick={(e) => this.props.onDestroy(e)}/>
                </div>
                <input
                    className="edit"
                    ref={input => this.textInput = input}
                    value={this.state.editText}
                    onBlur={() => this.handleSubmit()}
                    onChange={e => this.handleChange(e)}
                    onKeyDown={e => this.handleKeyDown(e)}
                />
            </li>
        );
    }
}

export default TodoItem;

// examples/stencil/src/components/todo/todo-item.tsx
import {Component, Prop, h, State, Event, EventEmitter} from '@stencil/core';
import {TodoItemModel} from "./todo-model";
import classNames from 'classnames';

const ESCAPE_KEY = 27;
const ENTER_KEY = 13;


@Component({
  tag: 'todo-item',
  styleUrl: 'todo-item.css',
  shadow: true
})
export class TodoItem {
  @Prop() todo: TodoItemModel;
  @Prop() editing: boolean;
  @State() editText: string;
  @Event() toggle: EventEmitter<string>;
  @Event() destroy: EventEmitter<string>;
  @Event() edit: EventEmitter<string>;
  @Event() save: EventEmitter<{todoId: string, text: string}>;
  @Event() cancel: EventEmitter<void>;

  handleSubmit() {
    let text = this.editText.trim();
    if (text && this.editing) {
      this.save.emit({todoId: this.todo.id, text});
      this.editText = text;
    } else {
      this.destroy.emit();
    }
  }

  handleChange(event) {
    if (this.editing) {
      this.editText = event.target.value;
    }
  }

  handleKeyDown(event: KeyboardEvent) {
    if (event.which === ESCAPE_KEY) {
      this.editText = this.todo.title;
      this.cancel.emit();
    } else if (event.which === ENTER_KEY) {
      this.handleSubmit();
    }
  }


  onToggle() {
    this.toggle.emit(this.todo.id);
  }

  handleEdit() {
    this.edit.emit(this.todo.id);
    this.editText = this.todo.title;
  }

  onDestroy() {
    this.destroy.emit(this.todo.id);
  }

  render() {
    return (
      <li class={classNames({
        completed: this.todo.completed,
        editing: this.editing
      })}>
        <div class="view">
          <input
            class="toggle"
            type="checkbox"
            checked={this.todo.completed}
            onChange={_ => this.onToggle()}
          />
          <label onDblClick={_ => this.handleEdit()}>
            {this.todo.title}
          </label>
          <button class="destroy" onClick={_ => this.onDestroy()} />
        </div>
        <input
          class="edit"
          value={this.editText}
          onBlur={_ => this.handleSubmit()}
          onInput={ev => this.handleChange(ev)}
          onKeyDown={ev => this.handleKeyDown(ev)}
        />
      </li>
    );
  }

}
