// examples/typescript-react/src/components/TodoFooter.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';

interface ITodoFooterProps {
  remainingTodosCount: number;
  completedCount: number;
  onClearCompleted: () => void;
}

const TodoFooter: React.FC<ITodoFooterProps> = (props) => {
  const { remainingTodosCount, completedCount, onClearCompleted } = props;

  const itemCountLabel = remainingTodosCount > 1 ? 'items' : 'item';

  return (
    <footer className="footer">
      <span className="todo-count">
        <strong>{remainingTodosCount}</strong> {itemCountLabel} left
      </span>
      <ul className="filters">
        <li>
          <NavLink exact to="/" activeClassName="selected">
            All
          </NavLink>
        </li>
        <li>
          <NavLink to="/active" activeClassName="selected">
            Active
          </NavLink>
        </li>
        <li>
          <NavLink to="/completed" activeClassName="selected">
            Completed
          </NavLink>
        </li>
      </ul>
      {completedCount > 0 && (
        <button className="clear-completed" onClick={onClearCompleted}>
          Clear completed
        </button>
      )}
    </footer>
  );
};

export default TodoFooter;

// updates/vue/src/components/TodoFooter.vue
<template>
    <footer class="footer" v-show="todos.length > 0">
        <span class="todo-count">
            <strong>{{ remaining }}</strong> {{ pluralizedWord }} left
        </span>
        <ul class="filters">
            <li><router-link to="/" :class="{ selected: route == 'all' }">All</router-link></li>
            <li><router-link to="/active" :class="{ selected: route == 'active' }">Active</router-link></li>
            <li><router-link to="/completed" :class="{ selected: route == 'completed' }">Completed</router-link></li>
        </ul>
        <button class="clear-completed" v-show="completed" @click="$emit('delete-completed')">Clear Completed</button>
    </footer>
</template>

<script>
export default {
    name: "TodoFooter",
    props: {
        todos: Array,
        remaining: Number,
        route: String,
        completed: Number,
    },
    computed: {
        pluralizedWord() {
            return this.remaining === 1 ? "item" : "items";
        },
    },
    emits: ["delete-completed"],
};
</script>
