// examples/svelte/src/routes/[[filter]]/components/TodoItem.svelte
<script>
import { createEventDispatcher, tick } from 'svelte';
import { KeyCodes } from '../../../constants';

const dispatch = createEventDispatcher();

export let todo;

let editing = false;

let editingTodo = { ...todo };

const focus = (el) => ({
  async update(params) {
    if (params) {
      await tick();
      el.focus();
    }
  },
});

const handleToggle = (event) => dispatch('complete', { completed: event.target.checked });

const handleRemove = () => dispatch('remove', todo);

const handleBeginEdit = () => {
  editing = true;
  editingTodo = { ...todo };
};

const finishEdit = () => {
  editing = false;
  const trimedTitle = editingTodo.title?.trim?.();
  if (trimedTitle.length > 0) {
    dispatch('edit', { ...editingTodo, title: trimedTitle, });
  } else {
    dispatch('remove', todo);
  }
};

const cancelEdit = () => {
  editing = false;
};

const handleEditKeydown = ({ keyCode }) => {
  switch (keyCode) {
    case KeyCodes.Enter:
      return finishEdit(todo);
    case KeyCodes.Escape:
      return cancelEdit();
  }
};
</script>

<li
  class="todo"
  class:completed={todo.completed}
  class:editing
>
  <div class="view">
    <input
      class="toggle"
      type="checkbox"
      checked={todo.completed}
      on:change={handleToggle}
    >
    <label on:dblclick={handleBeginEdit}>{todo.title}</label>
    <button class="destroy" on:click={handleRemove}></button>
  </div>
  <input 
    class="edit" 
    type="text" 
    bind:value={editingTodo.title}
    use:focus={editing}
    on:keydown={handleEditKeydown}
    on:blur={finishEdit}
  >
</li>

// updates/vue/src/components/TodoItem.vue
<template>
    <li
        :class="{
            completed: this.todo.completed,
            editing: this.editing,
        }"
    >
        <div class="view">
            <input type="checkbox" class="toggle" v-model="toggleModel" />
            <label @dblclick="startEdit">{{ todo.title }}</label>
            <button class="destroy" @click.prevent="deleteTodo"></button>
        </div>
        <div class="input-container">
            <input id="edit-todo-input" ref="editInputRef" type="text" class="edit" v-model="editModel" @keyup.enter="finishEdit" @blur="cancelEdit" />
            <label class="visually-hidden" for="edit-todo-input">Edit Todo Input</label>
        </div>
    </li>
</template>

<script>
import { nextTick } from "vue";
export default {
    name: "TodoItem",
    props: {
        todo: {
            title: String,
            completed: Boolean,
            id: Number,
        },
        index: Number,
    },
    data() {
        return {
            editText: "",
            editing: false,
        };
    },
    methods: {
        startEdit() {
            this.editing = true;
            nextTick(() => {
                this.focusEditInput();
            });
        },
        finishEdit() {
            this.editing = false;
            // prettier-ignore
            if (this.editText.trim().length === 0)
                this.deleteTodo();
            else
                this.updateTodo();
        },
        cancelEdit() {
            this.editing = false;
        },
        focusEditInput() {
            this.$refs.editInputRef.focus();
        },
        deleteTodo() {
            this.$emit("delete-todo", this.todo);
        },
        updateTodo() {
            this.$emit("edit-todo", this.todo, this.editText);
            this.editText = "";
        },
    },
    computed: {
        toggleModel: {
            get() {
                return this.todo.completed;
            },
            set(value) {
                this.$emit("toggle-todo", this.todo, value);
            },
        },
        editModel: {
            get() {
                return this.todo.title;
            },
            set(value) {
                this.editText = value;
            },
        },
    },
    emits: ["edit-todo", "delete-todo", "toggle-todo"],
};
</script>
