// examples/vue/src/components/TodoItem.vue
<script setup>
import { ref, nextTick } from 'vue'

const props = defineProps(['todo']);
const emit = defineEmits(['delete-todo', 'edit-todo', 'toggle-todo']);

const editing = ref(false);
const editInput = ref(null);
const draft = ref('');

function onToggle(event) {
    emit('toggle-todo', props.todo, event.target.checked);
}

function startEdit() {
    draft.value = props.todo.title;
    editing.value = true;
    nextTick(() => editInput.value?.focus());
}

function commitEdit() {
    if (!editing.value) return;
    editing.value = false;
    const text = draft.value.trim();
    if (text.length === 0) emit('delete-todo', props.todo);
    else emit('edit-todo', props.todo, text);
}

function cancelEdit() {
    editing.value = false;
    draft.value = props.todo.title;
}

function deleteTodo() {
    emit('delete-todo', props.todo);
}
</script>

<template>
    <li :class="{ completed: todo.completed, editing }">
        <div class="view">
            <input type="checkbox" class="toggle" :checked="todo.completed" @change="onToggle" />
            <label @dblclick="startEdit">{{ todo.title }}</label>
            <button class="destroy" @click.prevent="deleteTodo"></button>
        </div>
        <input
            v-if="editing"
            ref="editInput"
            type="text"
            class="edit"
            aria-label="Edit todo"
            v-model="draft"
            @keyup.enter="commitEdit"
            @keyup.escape="cancelEdit"
            @blur="commitEdit"
        />
    </li>
</template>

// examples/svelte/src/routes/[[filter]]/components/TodoItem.svelte
<script>
import { createEventDispatcher, tick } from 'svelte';
import { KeyCodes } from '../../../constants';

const dispatch = createEventDispatcher();

export let todo;

let editing = false;

let editingTodo = { ...todo };

const focus = (el) => ({
  async update(params) {
    if (params) {
      await tick();
      el.focus();
    }
  },
});

const handleToggle = (event) => dispatch('complete', { completed: event.target.checked });

const handleRemove = () => dispatch('remove', todo);

const handleBeginEdit = () => {
  editing = true;
  editingTodo = { ...todo };
};

const finishEdit = () => {
  editing = false;
  const trimedTitle = editingTodo.title?.trim?.();
  if (trimedTitle.length > 0) {
    dispatch('edit', { ...editingTodo, title: trimedTitle, });
  } else {
    dispatch('remove', todo);
  }
};

const cancelEdit = () => {
  editing = false;
};

const handleEditKeydown = ({ keyCode }) => {
  switch (keyCode) {
    case KeyCodes.Enter:
      return finishEdit(todo);
    case KeyCodes.Escape:
      return cancelEdit();
  }
};
</script>

<li
  class="todo"
  class:completed={todo.completed}
  class:editing
>
  <div class="view">
    <input
      class="toggle"
      type="checkbox"
      checked={todo.completed}
      on:change={handleToggle}
    >
    <label on:dblclick={handleBeginEdit}>{todo.title}</label>
    <button class="destroy" on:click={handleRemove}></button>
  </div>
  <input 
    class="edit" 
    type="text" 
    bind:value={editingTodo.title}
    use:focus={editing}
    on:keydown={handleEditKeydown}
    on:blur={finishEdit}
  >
</li>
