// examples/stencil/src/components/todo/todo-footer.tsx
import {Component, Prop, h, Event, EventEmitter} from '@stencil/core';
import {pluralize} from '../../utils/utils';
import {ALL_TODOS, ACTIVE_TODOS, COMPLETED_TODOS} from './showing-state';
import classNames from 'classnames';

@Component({
  tag: 'todo-footer',
  styleUrl: 'todo-footer.css',
  shadow: true
})
export class TodoFooter {

  @Prop() count: number;
  @Prop() completedCount: number;
  @Prop() nowShowing: string;
  @Event() clearCompleted: EventEmitter<void>;

  render() {
    let activeTodoWord = pluralize(this.count, 'item');
    let clearButton = null;

    if (this.completedCount > 0) {
      clearButton = (
        <button
          class="clear-completed"
          onClick={_ => this.clearCompleted.emit()}>
          Clear completed
        </button>
      );
    }

    let nowShowing = this.nowShowing;
    return (
      <footer class="footer">
					<span class="todo-count">
						<strong>{this.count}</strong> {activeTodoWord} left
					</span>
        <ul class="filters">
          <li>
            <a
              href="#/"
              class={classNames({selected: nowShowing === ALL_TODOS})}>
              All
            </a>
          </li>
          {' '}
          <li>
            <a
              href="#/active"
              class={classNames({selected: nowShowing === ACTIVE_TODOS})}>
              Active
            </a>
          </li>
          {' '}
          <li>
            <a
              href="#/completed"
              class={classNames({selected: nowShowing === COMPLETED_TODOS})}>
              Completed
            </a>
          </li>
        </ul>
        {clearButton}
      </footer>
    );
  }

}

// examples/typescript-react/src/components/TodoFooter.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';

interface ITodoFooterProps {
  remainingTodosCount: number;
  completedCount: number;
  onClearCompleted: () => void;
}

const TodoFooter: React.FC<ITodoFooterProps> = (props) => {
  const { remainingTodosCount, completedCount, onClearCompleted } = props;

  const itemCountLabel = remainingTodosCount > 1 ? 'items' : 'item';

  return (
    <footer className="footer">
      <span className="todo-count">
        <strong>{remainingTodosCount}</strong> {itemCountLabel} left
      </span>
      <ul className="filters">
        <li>
          <NavLink exact to="/" activeClassName="selected">
            All
          </NavLink>
        </li>
        <li>
          <NavLink to="/active" activeClassName="selected">
            Active
          </NavLink>
        </li>
        <li>
          <NavLink to="/completed" activeClassName="selected">
            Completed
          </NavLink>
        </li>
      </ul>
      {completedCount > 0 && (
        <button className="clear-completed" onClick={onClearCompleted}>
          Clear completed
        </button>
      )}
    </footer>
  );
};

export default TodoFooter;
