// examples/vue/src/components/TodoFooter.vue
<script setup>
import { computed } from 'vue';
import { useRoute, RouterLink } from 'vue-router';

const props = defineProps(['todos']);
const route = useRoute();
const remaining = computed(() => props.todos.filter(todo => !todo.completed).length);
</script>

<template>
    <footer class="footer" v-show="todos.length > 0">
        <span class="todo-count">
            <strong>{{ remaining }}</strong> {{ remaining === 1 ? "item" : "items" }} left
        </span>
        <ul class="filters">
            <li><RouterLink to="/" :class="{ selected: route.name == 'all' }">All</RouterLink></li>
            <li><RouterLink to="/active" :class="{ selected: route.name == 'active' }">Active</RouterLink></li>
            <li><RouterLink to="/completed" :class="{ selected: route.name == 'completed' }">Completed</RouterLink></li>
        </ul>
        <button class="clear-completed" v-show="todos.some(todo => todo.completed)" @click="$emit('delete-completed')">Clear completed</button>
    </footer>
</template>

// examples/typescript-react/src/components/TodoFooter.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';

interface ITodoFooterProps {
  remainingTodosCount: number;
  completedCount: number;
  onClearCompleted: () => void;
}

const TodoFooter: React.FC<ITodoFooterProps> = (props) => {
  const { remainingTodosCount, completedCount, onClearCompleted } = props;

  const itemCountLabel = remainingTodosCount > 1 ? 'items' : 'item';

  return (
    <footer className="footer">
      <span className="todo-count">
        <strong>{remainingTodosCount}</strong> {itemCountLabel} left
      </span>
      <ul className="filters">
        <li>
          <NavLink exact to="/" activeClassName="selected">
            All
          </NavLink>
        </li>
        <li>
          <NavLink to="/active" activeClassName="selected">
            Active
          </NavLink>
        </li>
        <li>
          <NavLink to="/completed" activeClassName="selected">
            Completed
          </NavLink>
        </li>
      </ul>
      {completedCount > 0 && (
        <button className="clear-completed" onClick={onClearCompleted}>
          Clear completed
        </button>
      )}
    </footer>
  );
};

export default TodoFooter;
