// examples/svelte/src/Item.svelte
<script>
    import { tick } from 'svelte';

    let { item, onRemoveItem } = $props();

    let editing = $state(false);

    function startEdit() {
        editing = true;
    }

    function handleEdit(event) {
        if (event.key === "Enter")
            event.target.blur();
        else if (event.key === "Escape")
            editing = false;
    }

    function updateItem(event) {
        if (!editing) return;
        const { value } = event.target;
        if (value.length) {
            item.description = value;
        } else {
            onRemoveItem();
        }
        editing = false;
    }

    async function focusInput(element) {
        await tick();
        element.focus();
    }
</script>

<li class:completed={item.completed} class:editing>
    <div class="view">
        <input class="toggle" type="checkbox" onchange={(event) => item.completed = event.target.checked} checked={item.completed} />
        <!-- svelte-ignore a11y_label_has_associated_control -->
        <label ondblclick={startEdit}>{item.description}</label>
        <button onclick={onRemoveItem} class="destroy" aria-label="Delete"></button>
    </div>

    {#if editing}
        <input
            value={item.description}
            class="edit"
            aria-label="Edit todo"
            onkeydown={handleEdit}
            onblur={updateItem}
            use:focusInput
        />
    {/if}
</li>

// examples/react-redux/src/components/item.jsx
import { memo, useState } from "react";
import classnames from "classnames";
import { useDispatch } from "react-redux";
import TextInput from "./text-input";
import { editTodo, deleteTodo, toggleTodo } from "../store";

function Item({ todo }) {
    const dispatch = useDispatch();
    const [editing, setEditing] = useState(false);

    const handleSave = (text) => {
        if (text.length === 0) dispatch(deleteTodo(todo.id));
        else dispatch(editTodo({ id: todo.id, text }));
        setEditing(false);
    };

    const view = editing ? (
        <TextInput text={todo.text} editing onSave={handleSave} />
    ) : (
        <div className="view">
            <input
                className="toggle"
                type="checkbox"
                data-testid="todo-item-toggle"
                checked={todo.completed}
                onChange={() => dispatch(toggleTodo(todo.id))}
            />
            <label onDoubleClick={() => setEditing(true)} data-testid="todo-item-label">
                {todo.text}
            </label>
            <button
                className="destroy"
                data-testid="todo-item-button"
                aria-label="Delete"
                onClick={() => dispatch(deleteTodo(todo.id))}
            />
        </div>
    );

    return (
        <li
            className={classnames({ completed: todo.completed, editing })}
            data-testid="todo-item"
        >
            {view}
        </li>
    );
}

export default memo(Item);
