// updates/angular/src/app/todo-footer/todo-footer.component.ts
import { Component } from "@angular/core";
import { Location } from "@angular/common";
import { Todo } from "../todo";
import { TodosService } from "../todos.service";

@Component({
    selector: "app-todo-footer",
    templateUrl: "./todo-footer.component.html",
})
export class TodoFooterComponent {
    constructor(private todosService: TodosService, private location: Location) {}

    get todos(): Todo[] {
        return this.todosService.getItems();
    }

    get activeTodos(): Todo[] {
        return this.todosService.getItems("active");
    }

    get completedTodos(): Todo[] {
        return this.todosService.getItems("completed");
    }

    get filter(): string {
        return this.location.path().split("/")[1] || "all";
    }

    clearCompleted() {
        this.todosService.clearCompleted();
    }
}

<footer class="footer" *ngIf="todos.length > 0">
    <span class="todo-count"
        ><strong>{{ activeTodos.length }}</strong> {{ activeTodos.length == 1 ? "item" : "items" }} left</span
    >
    <ul class="filters">
        <li>
            <a routerLink="/" [class.selected]="filter === 'all'"> All </a>
        </li>
        <li>
            <a routerLink="/active" [class.selected]="filter === 'active'"> Active </a>
        </li>
        <li>
            <a routerLink="/completed" [class.selected]="filter === 'completed'"> Completed </a>
        </li>
    </ul>
    <button *ngIf="completedTodos.length" type="button" class="clear-completed" (click)="clearCompleted()">Clear Completed</button>
</footer>

// examples/vue/src/components/TodoFooter.vue
<script setup>
import { computed } from 'vue';
import { useRoute, RouterLink } from 'vue-router';

const props = defineProps(['todos']);
const route = useRoute();
const remaining = computed(() => props.todos.filter(todo => !todo.completed).length);
</script>

<template>
    <footer class="footer" v-show="todos.length > 0">
        <span class="todo-count">
            <strong>{{ remaining }}</strong> {{ remaining === 1 ? "item" : "items" }} left
        </span>
        <ul class="filters">
            <li><RouterLink to="/" :class="{ selected: route.name == 'all' }">All</RouterLink></li>
            <li><RouterLink to="/active" :class="{ selected: route.name == 'active' }">Active</RouterLink></li>
            <li><RouterLink to="/completed" :class="{ selected: route.name == 'completed' }">Completed</RouterLink></li>
        </ul>
        <button class="clear-completed" v-show="todos.some(todo => todo.completed)" @click="$emit('delete-completed')">Clear completed</button>
    </footer>
</template>
