// examples/firebase-angular2/src/app/components/todo-header/todo-header.component.ts
import { Component, OnInit } from '@angular/core';

import { TodoStoreService } from '../../services/todo-store.service';
import { TodoModel } from 'app/models/todo.model';

@Component({
  selector: 'todo-header',
  templateUrl: './todo-header.component.html',
})
export class TodoHeaderComponent implements OnInit {

  newTodo = '';

  constructor(private todoStore: TodoStoreService) { }

  ngOnInit() {
  }

  addTodo() {
    if (this.newTodo.trim().length) {
      this.todoStore.add(new TodoModel(this.newTodo));
      this.newTodo = '';
    }
  }

}

<header class="header">
  <h1>todos</h1>
  <input class="new-todo" placeholder="What needs to be done?" [(ngModel)]="newTodo" autofocus="" (keyup.enter)="addTodo()">
</header>

// examples/vue/src/components/TodoHeader.vue
<script setup>
import { RouterLink } from 'vue-router';

const emit = defineEmits(['add-todo']);

function onEnter(event) {
    const text = event.target.value.trim();
    if (text.length === 0) return;
    emit('add-todo', text);
    event.target.value = '';
}
</script>

<template>
    <header class="header">
        <RouterLink to="/"><h1>todos</h1></RouterLink>
        <input
            type="text"
            class="new-todo"
            autofocus
            autocomplete="off"
            placeholder="What needs to be done?"
            @keyup.enter="onEnter"
        />
    </header>
</template>
