// examples/react-redux/js/components/TodoList.jsx
import React, { PropTypes } from 'react';
import Todo from '../containers/Todo';

export default class TodoList extends React.Component {

	static propTypes = {
		actions: PropTypes.shape({
			toggleAll: PropTypes.func.isRequired
		}).isRequired,
		todos: PropTypes.arrayOf(PropTypes.shape({
			id: PropTypes.string.isRequired,
			completed: PropTypes.bool.isRequired
		}).isRequired).isRequired
	}

	constructor(props) {
		super(props);
		this.toggleAll = this.toggleAll.bind(this);
	}

	render() {
		const todos = this.props.todos.map(todo => (
			<Todo
				key={todo.id}
				{...todo}
			/>
		));

		const allCompleted = !this.props.todos.find(todo => !todo.completed);

		return (
			<section className="main">
				<input type="checkbox"
					className="toggle-all"
					checked={allCompleted}
					onChange={this.toggleAll}/>
				<ul className="todo-list">
					{todos}
				</ul>
			</section>
		)
	}

	toggleAll () {
		this.props.actions.toggleAll();
	}
}

// examples/svelte/js/components/TodoList.svelte
<script>
	import { onMount } from 'svelte';
	import Todo from './Todo.svelte';
	import { ALL, ACTIVE, COMPLETED } from '../helpers/filterCodes';

	export let todos = [];
	export let visible = true;
	export let filterBy = ALL;

	let toggleAllEl = null;
	let filteredList = ALL;

	const handleToggleAll = e => todos.toggleAll(e.target.checked);

	$: allCompleted = $todos.every(todo => todo.completed);
	$: switch (filterBy) {
		case ACTIVE:
			filteredList = $todos.filter(todo => !todo.completed);
			break;
		case COMPLETED:
			filteredList = $todos.filter(todo => todo.completed);
			break;
		default:
			filteredList = $todos;
	};
</script>

{#if $visible}
	<section class="main" data-testid="main">
		<input
			id="toggle-all"
			class="toggle-all"
			type="checkbox"
			data-testid="toggle-all"
			bind:checked={allCompleted}
			on:click={handleToggleAll}
		>
		<label for="toggle-all">Mark all as complete</label>
		<ul class="todo-list">
			{#each filteredList as todo (todo.id)}
				<Todo {todos} {todo}/>
			{/each}
		</ul>
	</section>
{/if}
