// examples/firebase-angular2/src/app/app.component.ts
import { Component } from '@angular/core';

import 'rxjs/Rx';

@Component({
  selector: 'todo-app',
  templateUrl: './app.component.html',
})
export class AppComponent {
  title = 'app';
}

<router-outlet></router-outlet>
<footer class="info">
    <p>Double-click to edit a todo</p>
    <p>Written by <a href="https://github.com/pablo-albaladejo">Pablo Albaladejo</a></p>    
    <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
</footer>

// examples/typescript-vue/src/App.vue
<template>
  <div id='app'>
    <section class="todoapp">
      <Header/>
      <TodoList />
      <Footer/>
    </section>
    <footer class="info">
      <p>Double-click to edit a todo</p>
      <p>Written by <a href="https://github.com/victorgarciaesgi">Victor Garcia</a></p>
      <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
    </footer>
  </div>
</template>


<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";

import { store } from "@store";
import { Header, TodoList, Footer } from "@components";
import { State, Getter, Mutation, Action, namespace } from "vuex-class";

const TodoAction = namespace("TodoModule", Action);

@Component({
  components: {
    Header,
    TodoList,
    Footer
  },
  store
})
export default class App extends Vue {
  @TodoAction changeVisibility;

  mounted() {
    window.addEventListener("hashchange", this.onHashChange);
    this.onHashChange();
  }

  onHashChange() {
    let visibility = window.location.hash.replace(/#\/?/, "");
    this.changeVisibility(visibility);
  }
}
</script>
