// examples/vue/src/components/TodoItem.vue
<script setup>
import { ref, nextTick } from 'vue'

const props = defineProps(['todo']);
const emit = defineEmits(['delete-todo', 'edit-todo', 'toggle-todo']);

const editing = ref(false);
const editInput = ref(null);
const draft = ref('');

function onToggle(event) {
    emit('toggle-todo', props.todo, event.target.checked);
}

function startEdit() {
    draft.value = props.todo.title;
    editing.value = true;
    nextTick(() => editInput.value?.focus());
}

function commitEdit() {
    if (!editing.value) return;
    editing.value = false;
    const text = draft.value.trim();
    if (text.length === 0) emit('delete-todo', props.todo);
    else emit('edit-todo', props.todo, text);
}

function cancelEdit() {
    editing.value = false;
    draft.value = props.todo.title;
}

function deleteTodo() {
    emit('delete-todo', props.todo);
}
</script>

<template>
    <li :class="{ completed: todo.completed, editing }">
        <div class="view">
            <input type="checkbox" class="toggle" :checked="todo.completed" @change="onToggle" />
            <label @dblclick="startEdit">{{ todo.title }}</label>
            <button class="destroy" @click.prevent="deleteTodo"></button>
        </div>
        <input
            v-if="editing"
            ref="editInput"
            type="text"
            class="edit"
            aria-label="Edit todo"
            v-model="draft"
            @keyup.enter="commitEdit"
            @keyup.escape="cancelEdit"
            @blur="commitEdit"
        />
    </li>
</template>

// examples/angular/src/app/todo-item/todo-item.component.ts
import { Component, ElementRef, EventEmitter, Input, Output, ViewChild, AfterViewChecked } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Todo } from '../todos.service';

@Component({
  selector: 'app-todo-item',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './todo-item.component.html',
})
export class TodoItemComponent implements AfterViewChecked {
  @Input({ required: true }) todo!: Todo;

  @Output() remove = new EventEmitter<Todo>();

  @ViewChild('todoInputRef') inputRef?: ElementRef<HTMLInputElement>;

  title = '';
  isEditing = false;

  // Track which edit session we've already focused so we don't re-focus
  // on every change-detection pass while editing.
  private focusedFor: Todo | null = null;

  toggleTodo(): void {
    this.todo.completed = !this.todo.completed;
  }

  removeTodo(): void {
    this.remove.emit(this.todo);
  }

  startEdit(): void {
    this.isEditing = true;
  }

  handleFocus(_event: Event): void {
    this.title = this.todo.title;
  }

  commitEdit(): void {
    if (!this.isEditing) return;
    const text = this.title.trim();
    this.isEditing = false;
    if (text.length === 0) {
      this.remove.emit(this.todo);
    } else {
      this.todo.title = text;
    }
  }

  cancelEdit(): void {
    this.title = this.todo.title;
    this.isEditing = false;
  }

  ngAfterViewChecked(): void {
    if (this.isEditing && this.focusedFor !== this.todo) {
      this.inputRef?.nativeElement.focus();
      this.focusedFor = this.todo;
    } else if (!this.isEditing && this.focusedFor) {
      this.focusedFor = null;
    }
  }
}

<li [class.completed]="todo.completed" [class.editing]="isEditing">
    <div class="view">
        <input class="toggle" type="checkbox" (change)="toggleTodo()" [checked]="todo.completed" />
        <label (dblclick)="startEdit()">{{ todo.title }}</label>
        <button class="destroy" aria-label="Delete todo" (click)="removeTodo()"></button>
    </div>
    @if (isEditing) {
        <input
            #todoInputRef
            class="edit"
            aria-label="Edit todo"
            [(ngModel)]="title"
            (focus)="handleFocus($event)"
            (blur)="commitEdit()"
            (keyup.enter)="commitEdit()"
            (keyup.escape)="cancelEdit()" />
    }
</li>
