// examples/react-hooks/src/index.js
import "core-js/es6/map";
import "core-js/es6/set";
import "raf/polyfill";

import React from "react";
import ReactDOM from "react-dom";

import "./index.css";
import App from "./App/App";
import * as serviceWorker from "./serviceWorker";

const root = document.getElementById("root");
ReactDOM.render(<App />, root);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.register();

// examples/solid/src/index.js
import { render } from 'solid-js/web';
import App from './components/App';
import * as serviceWorker from './serviceWorker';

import 'todomvc-common/base.css';
import 'todomvc-app-css/index.css';

render(App, document.querySelector('section.todoapp'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
