// examples/svelte/src/Item.svelte
<script>
    import { tick } from 'svelte';

    let { item, onRemoveItem } = $props();

    let editing = $state(false);

    function startEdit() {
        editing = true;
    }

    function handleEdit(event) {
        if (event.key === "Enter")
            event.target.blur();
        else if (event.key === "Escape")
            editing = false;
    }

    function updateItem(event) {
        if (!editing) return;
        const { value } = event.target;
        if (value.length) {
            item.description = value;
        } else {
            onRemoveItem();
        }
        editing = false;
    }

    async function focusInput(element) {
        await tick();
        element.focus();
    }
</script>

<li class:completed={item.completed} class:editing>
    <div class="view">
        <input class="toggle" type="checkbox" onchange={(event) => item.completed = event.target.checked} checked={item.completed} />
        <!-- svelte-ignore a11y_label_has_associated_control -->
        <label ondblclick={startEdit}>{item.description}</label>
        <button onclick={onRemoveItem} class="destroy" aria-label="Delete"></button>
    </div>

    {#if editing}
        <input
            value={item.description}
            class="edit"
            aria-label="Edit todo"
            onkeydown={handleEdit}
            onblur={updateItem}
            use:focusInput
        />
    {/if}
</li>

// examples/react/src/todo/components/item.jsx
import { memo, useState, useCallback } from "react";
import classnames from "classnames";

import { Input } from "./input";

import { TOGGLE_ITEM, REMOVE_ITEM, UPDATE_ITEM } from "../constants";

export const Item = memo(function Item({ todo, dispatch }) {
    const [isWritable, setIsWritable] = useState(false);
    const { title, completed, id } = todo;

    const toggleItem = useCallback(() => dispatch({ type: TOGGLE_ITEM, payload: { id } }), [dispatch, id]);
    const removeItem = useCallback(() => dispatch({ type: REMOVE_ITEM, payload: { id } }), [dispatch, id]);
    const updateItem = useCallback(
        (newTitle) => dispatch({ type: UPDATE_ITEM, payload: { id, title: newTitle } }),
        [dispatch, id]
    );

    const handleDoubleClick = useCallback(() => setIsWritable(true), []);

    const commitEdit = useCallback(
        (newTitle) => {
            // Only act once per edit session — Enter then blur would
            // otherwise dispatch twice.
            if (!isWritable) return;
            setIsWritable(false);
            if (newTitle.length === 0) removeItem();
            else updateItem(newTitle);
        },
        [isWritable, removeItem, updateItem]
    );

    return (
        <li className={classnames({ completed, editing: isWritable })} data-testid="todo-item">
            <div className="view">
                <input
                    className="toggle"
                    type="checkbox"
                    data-testid="todo-item-toggle"
                    checked={completed}
                    onChange={toggleItem}
                />
                <label data-testid="todo-item-label" onDoubleClick={handleDoubleClick}>
                    {title}
                </label>
                <button
                    className="destroy"
                    data-testid="todo-item-button"
                    aria-label="Delete todo"
                    onClick={removeItem}
                />
            </div>
            {isWritable && (
                <Input
                    editing
                    onSubmit={commitEdit}
                    onBlur={commitEdit}
                    label="Edit todo"
                    defaultValue={title}
                />
            )}
        </li>
    );
});
