// examples/svelte/src/Footer.svelte
<script>
    let { numActive, currentFilter, numCompleted, onRemoveCompletedItems } = $props();
</script>

<footer class="footer">
    <span class="todo-count">
        <strong>{numActive}</strong>
        {numActive === 1 ? "item" : "items"} left
    </span>

    <ul class="filters">
        <li><a class:selected={currentFilter === "all"} href="#/">All</a></li>
        <li><a class:selected={currentFilter === "active"} href="#/active">Active</a></li>
        <li><a class:selected={currentFilter === "completed"} href="#/completed">Completed</a></li>
    </ul>

    {#if numCompleted}
        <button class="clear-completed" onclick={onRemoveCompletedItems}> Clear completed </button>
    {/if}
</footer>

// examples/solid/src/components/Footer.jsx
import { Show } from "solid-js";
import { clearCompleted, state } from "../utils/store"

function Footer() {
	const count = () => state.todos.filter(todo => !todo.completed).length;
	const completedExists = () => state.todos.some(todo => todo.completed);

	return <footer class="footer">
		<span class="todo-count"><strong>{count()}</strong> item left</span>
		<ul class="filters">
			<li>
				<a class="selected" href="#/">All</a>
			</li>
			<li>
				<a href="#/active">Active</a>
			</li>
			<li>
				<a href="#/completed">Completed</a>
			</li>
		</ul>
		<Show when={completedExists()}>
			<button class="clear-completed" onClick={clearCompleted}>Clear completed</button>
		</Show>
	</footer>
}

export default Footer;
