// examples/solid/src/components/TodoItem.jsx
import { createSignal } from "solid-js";
import { editTodo, removeTodo, setIsTodoCompleted } from "../utils/store";
import classNames from 'classnames';
import { onClickOutside } from '../utils/clickoutside'

function TodoItem(props) {
	const [isEditing, setIsEditing] = createSignal(false)
	let ref;

	onClickOutside(ref, () => setIsEditing(false));

  return <li class={classNames({ completed: props.completed, editing: isEditing()})} onDblClick={() => setIsEditing(true)}>
		<div class="view">
			<input
				class="toggle"
				type="checkbox"
				checked={props.completed}
				onChange={e => setIsTodoCompleted(props.id, e.target.checked)}
			/>
			<label>{props.title}</label>
			<button class="destroy" onClick={() => removeTodo(props.id)}></button>
		</div>
		<input ref={ref} class="edit" value={props.title} onInput={e => editTodo(props.id, e.currentTarget.value)} />
	</li>
}

export default TodoItem;

// examples/react-hooks/src/containers/TodoItem.js
import React, { useCallback, useRef, useState } from "react";
import useOnClickOutside from "use-onclickoutside";

import useDoubleClick from "../hooks/useDoubleClick";
import useOnEnter from "../hooks/useOnEnter";
import useTodos from "../reducers/useTodos";

export default function TodoItem({ todo }) {
  const [, { deleteTodo, setLabel, toggleDone }] = useTodos(() => null);

  const [editing, setEditing] = useState(false);

  const onDelete = useCallback(() => deleteTodo(todo.id), [todo.id]);
  const onDone = useCallback(() => toggleDone(todo.id), [todo.id]);
  const onChange = useCallback(event => setLabel(todo.id, event.target.value), [
    todo.id
  ]);

  const handleViewClick = useDoubleClick(null, () => setEditing(true));
  const finishedCallback = useCallback(
    () => {
      setEditing(false);
      setLabel(todo.id, todo.label.trim());
    },
    [todo]
  );

  const onEnter = useOnEnter(finishedCallback, [todo]);
  const ref = useRef();
  useOnClickOutside(ref, finishedCallback);

  return (
    <li
      onClick={handleViewClick}
      className={`${editing ? "editing" : ""} ${todo.done ? "completed" : ""}`}
    >
      <div className="view">
        <input
          type="checkbox"
          className="toggle"
          checked={todo.done}
          onChange={onDone}
          autoFocus={true}
        />
        <label>{todo.label}</label>
        <button className="destroy" onClick={onDelete} />
      </div>
      {editing && (
        <input
          ref={ref}
          className="edit"
          value={todo.label}
          onChange={onChange}
          onKeyPress={onEnter}
        />
      )}
    </li>
  );
}
