// examples/vue/src/components/TodoHeader.vue
<script setup>
import { RouterLink } from 'vue-router';

const emit = defineEmits(['add-todo']);

function onEnter(event) {
    const text = event.target.value.trim();
    if (text.length === 0) return;
    emit('add-todo', text);
    event.target.value = '';
}
</script>

<template>
    <header class="header">
        <RouterLink to="/"><h1>todos</h1></RouterLink>
        <input
            type="text"
            class="new-todo"
            autofocus
            autocomplete="off"
            placeholder="What needs to be done?"
            @keyup.enter="onEnter"
        />
    </header>
</template>

// updates/angular/src/app/todo-header/todo-header.component.ts
import { Component } from "@angular/core";
import { FormControl } from "@angular/forms";
import { TodosService } from "../todos.service";

@Component({
    selector: "app-todo-header",
    templateUrl: "./todo-header.component.html",
})
export class TodoHeaderComponent {
    constructor(private todosService: TodosService) {}

    titleFormControl = new FormControl("");

    addTodo() {
        const title = this.titleFormControl.getRawValue()?.trim();

        if (!title)
            return;

        this.todosService.addItem(title);
        this.titleFormControl.setValue("");
    }
}

<header class="header">
    <h1>todos</h1>
    <input class="new-todo" placeholder="What needs to be done?" autofocus="" [formControl]="titleFormControl" (keyup.enter)="addTodo()" />
</header>
