// updates/vue/src/components/TodoHeader.vue
<template>
    <header class="header">
        <h1>todos</h1>
        <input
            type="text"
            class="new-todo"
            autofocus
            autocomplete="off"
            placeholder="What needs to be done?"
            @keyup.enter="
                $emit('add-todo', $event.target.value);
                $event.target.value = '';
            "
        />
    </header>
</template>

<script>
export default {
    name: "TodoHeader",
    emits: ["add-todo"],
};
</script>

// updates/angular/src/app/todo-header/todo-header.component.ts
import { Component } from "@angular/core";
import { FormControl } from "@angular/forms";
import { TodosService } from "../todos.service";

@Component({
    selector: "app-todo-header",
    templateUrl: "./todo-header.component.html",
})
export class TodoHeaderComponent {
    constructor(private todosService: TodosService) {}

    titleFormControl = new FormControl("");

    addTodo() {
        const title = this.titleFormControl.getRawValue()?.trim();

        if (!title)
            return;

        this.todosService.addItem(title);
        this.titleFormControl.setValue("");
    }
}

<header class="header">
    <h1>todos</h1>
    <input class="new-todo" placeholder="What needs to be done?" autofocus="" [formControl]="titleFormControl" (keyup.enter)="addTodo()" />
</header>
