// examples/vue/src/components/TodoItem.vue
<script setup>
import { ref, nextTick } from 'vue'

const props = defineProps(['todo']);
const emit = defineEmits(['delete-todo', 'edit-todo', 'toggle-todo']);

const editing = ref(false);
const editInput = ref(null);
const draft = ref('');

function onToggle(event) {
    emit('toggle-todo', props.todo, event.target.checked);
}

function startEdit() {
    draft.value = props.todo.title;
    editing.value = true;
    nextTick(() => editInput.value?.focus());
}

function commitEdit() {
    if (!editing.value) return;
    editing.value = false;
    const text = draft.value.trim();
    if (text.length === 0) emit('delete-todo', props.todo);
    else emit('edit-todo', props.todo, text);
}

function cancelEdit() {
    editing.value = false;
    draft.value = props.todo.title;
}

function deleteTodo() {
    emit('delete-todo', props.todo);
}
</script>

<template>
    <li :class="{ completed: todo.completed, editing }">
        <div class="view">
            <input type="checkbox" class="toggle" :checked="todo.completed" @change="onToggle" />
            <label @dblclick="startEdit">{{ todo.title }}</label>
            <button class="destroy" @click.prevent="deleteTodo"></button>
        </div>
        <input
            v-if="editing"
            ref="editInput"
            type="text"
            class="edit"
            aria-label="Edit todo"
            v-model="draft"
            @keyup.enter="commitEdit"
            @keyup.escape="cancelEdit"
            @blur="commitEdit"
        />
    </li>
</template>

// examples/firebase-angular2/src/app/components/todo-item/todo-item.component.ts
import { Component, OnInit, EventEmitter, Output, Input } from '@angular/core';

@Component({
  selector: 'todo-item',
  templateUrl: './todo-item.component.html',
})
export class TodoItemComponent implements OnInit {

  @Input() todo;

  @Output() itemModified = new EventEmitter();

  @Output() itemRemoved = new EventEmitter();

  editing = false;

  constructor() { }

  ngOnInit() {
  }

  cancelEditing() {
    this.editing = false;
  }

  stopEditing(editedTitle) {
    this.todo.title = editedTitle.value;
    this.editing = false;

    if (this.todo.title.length === 0) {
      this.remove();
    } else {
      this.update();
    }
  }

  edit() {
    this.editing = true;
  }

  toggleCompletion() {
    this.todo.completed = !this.todo.completed;
    this.update();
  }

  remove() {
    this.itemRemoved.next(this.todo.uid);
  }

  update() {
    this.todo.title = this.todo.title.trim();
    this.itemModified.next(this.todo);
  }
}

<li [class.completed]="todo.completed" [class.editing]="editing">
  <div class="view">
    <input class="toggle" type="checkbox" (click)="toggleCompletion()" [checked]="todo.completed">
    <label (dblclick)="edit()">{{ todo.title | trim }}</label>
    <button class="destroy" (click)="remove()"></button>
  </div>
  <input class="edit" *ngIf="editing" [value]="todo.title" #editedtodo (blur)="stopEditing(editedtodo)" (keyup.enter)="stopEditing(editedtodo)"
    (keyup.escape)="cancelEditing()">
</li>
