// examples/typescript-vue/src/components/Header.vue
<template>
   <header class="header">
      <h1>todos</h1>
      <input class="new-todo"
        autofocus autocomplete="off"
        placeholder="What needs to be done?"
        v-model="newTodo"
        @keyup.enter="add">
    </header>
</template>


<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import { State, Mutation, Action, namespace } from "vuex-class";
import { ITodosState } from "@types";

const TodoAction = namespace("TodoModule", Action);

@Component({})
export default class Header extends Vue {
  @TodoAction addTodoAction;
  public newTodo: string = "";

  add() {
    if (this.newTodo.length) {
      this.addTodoAction(this.newTodo.trim());
      this.newTodo = "";
    }
  }
}
</script>

// examples/svelte/src/Header.svelte
<script>
    let { onAddItem } = $props();

    function addItem(e) {
        if (e.key !== 'Enter') return;
        const text = e.target.value.trim();
        if (text.length === 0) return;
        onAddItem(text);
        e.target.value = "";
    }
</script>

<header class="header">
    <h1>todos</h1>
    <!-- svelte-ignore a11y_autofocus -->
    <input class="new-todo" onkeydown={addItem} placeholder="What needs to be done?" autofocus />
</header>
