// updates/react/src/todo/components/header.jsx
import { useCallback } from "react";
import { Input } from "./input";

export function Header({ dispatch }) {
    const addItem = useCallback((title) => dispatch({ type: "ADD_ITEM", payload: { title } }), [dispatch]);

    return (
        <header className="header" data-testid="header">
            <h1>todos</h1>
            <Input onSubmit={addItem} label="New Todo Input" placeholder="What needs to be done?" />
        </header>
    );
}

// examples/svelte/src/Header.svelte
<script>
    import { createEventDispatcher } from 'svelte';

    const dispatch = createEventDispatcher();

    function addItem(e) {
        if (e.key !== 'Enter') return;
        dispatch('addItem', {
            text: e.target.value
        });
        e.target.value = "";
    }
</script>

<header class="header">
    <h1>todos</h1>
    <!-- svelte-ignore a11y-autofocus -->
    <input class="new-todo" on:keydown={addItem} placeholder="What needs to be done?" autofocus />
</header>
