// examples/angular/src/app/header/header.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TodosService } from '../todos.service';

@Component({
  standalone: true,
  selector: 'app-todo-header',
  imports: [FormsModule],
  templateUrl: './header.component.html',
})
export class HeaderComponent {
  private todosService = inject(TodosService);

  title = '';

  addTodo() {
    const text = this.title.trim();
    if (text.length === 0) return;
    this.todosService.addItem(text);
    // Reset title to clear input field.
    this.title = '';
  }
}

<header class="header">
  <h1>Todos</h1>
  <input class="new-todo"
    [(ngModel)]="title"
    autofocus=""
    placeholder="What needs to be done?"
    (keyup.enter)="addTodo()" />
</header>

// examples/svelte/src/Header.svelte
<script>
    let { onAddItem } = $props();

    function addItem(e) {
        if (e.key !== 'Enter') return;
        const text = e.target.value.trim();
        if (text.length === 0) return;
        onAddItem(text);
        e.target.value = "";
    }
</script>

<header class="header">
    <h1>todos</h1>
    <!-- svelte-ignore a11y_autofocus -->
    <input class="new-todo" onkeydown={addItem} placeholder="What needs to be done?" autofocus />
</header>
